services:
  backend-api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    x-develop:
      watch:
        - action: sync
          path: ./api
          target: ./api
    # image: semantic-search-api:latest
    ports:
      - 8000:8000
    volumes:
      - ./api:/app/api
    networks:
      - project_network
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    x-develop:
      watch:
        - action: sync
          path: ./frontend
          target: ./frontend
    # image: semantic-search-frontend:latest
    ports:
      - 8501:8501
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend-api
    networks:
      - project_network

networks:
  project_network:
